#!/usr/bin/env php
<?php
/**
 * 快速修复：从 config.example.php 创建 config.php 并添加 Cuisine
 */

echo "\n🔧 快速修复工具\n";
echo str_repeat("=", 60) . "\n\n";

$configFile = __DIR__ . '/config.php';
$exampleFile = __DIR__ . '/config.example.php';

if (file_exists($configFile)) {
    echo "⚠️  config.php 已存在\n";
    echo "\n是否查看当前配置? (y/n): ";
    $view = trim(fgets(STDIN));

    if (strtolower($view) === 'y') {
        echo "\n📄 当前 config.php:\n";
        echo str_repeat("-", 60) . "\n";
        echo file_get_contents($configFile);
        echo "\n" . str_repeat("-", 60) . "\n";
    }

    echo "\n请选择操作:\n";
    echo "  1) 添加 Cuisine 到现有配置\n";
    echo "  2) 覆盖创建新配置\n";
    echo "  3) 退出\n";
    echo "选择 (1-3): ";
    $choice = trim(fgets(STDIN));

    if ($choice === '3') {
        echo "👋 已退出\n";
        exit(0);
    }

    if ($choice === '2') {
        $backup = $configFile . '.backup-' . date('YmdHis');
        copy($configFile, $backup);
        echo "✅ 已备份到: $backup\n\n";
        unlink($configFile);
    }
}

if (!file_exists($configFile)) {
    // 从 example 创建
    if (!file_exists($exampleFile)) {
        die("❌ 错误: config.example.php 不存在\n");
    }

    echo "📋 请提供以下信息:\n\n";

    echo "Home Assistant URL (例如 http://192.168.1.100:8123): ";
    $haUrl = trim(fgets(STDIN));

    echo "Access Token: ";
    $token = trim(fgets(STDIN));

    echo "\n传感器 Entity IDs:\n";
    echo "YY 温度 (例如 sensor.wen_shi_du_chuan_gan_qi_yy_temperature): ";
    $yyTemp = trim(fgets(STDIN));

    echo "YY 湿度 (例如 sensor.wen_shi_du_chuan_gan_qi_yy_humidity): ";
    $yyHum = trim(fgets(STDIN));

    echo "\n是否添加 Cuisine (厨房)? (y/n): ";
    $addCuisine = trim(fgets(STDIN));

    $cuisineTemp = '';
    $cuisineHum = '';

    if (strtolower($addCuisine) === 'y') {
        echo "Cuisine 温度: ";
        $cuisineTemp = trim(fgets(STDIN));

        echo "Cuisine 湿度: ";
        $cuisineHum = trim(fgets(STDIN));
    }

    // 生成配置
    $config = <<<PHP
<?php
/**
 * Configuration pour Home Assistant Dashboard
 * Generated by quick-fix.php
 */

return [
    'home_assistant_url' => '$haUrl',
    'access_token' => '$token',
    'timeout' => 10,

    'sensor_groups' => [
        [
            'id' => 'yy_room',
            'name' => [
                'fr' => 'Chambre de YY',
                'en' => 'YY\\'s Room',
                'zh' => 'YY的房间',
            ],
            'sensors' => [
                [
                    'type' => 'temperature',
                    'entity_id' => '$yyTemp',
                    'icon' => '🌡️',
                    'name' => [
                        'fr' => 'Température',
                        'en' => 'Temperature',
                        'zh' => '温度',
                    ],
                ],
                [
                    'type' => 'humidity',
                    'entity_id' => '$yyHum',
                    'icon' => '💧',
                    'name' => [
                        'fr' => 'Humidité',
                        'en' => 'Humidity',
                        'zh' => '湿度',
                    ],
                ],
            ],
        ],

PHP;

    if (strtolower($addCuisine) === 'y' && $cuisineTemp && $cuisineHum) {
        $config .= <<<PHP
        [
            'id' => 'cuisine',
            'name' => [
                'fr' => 'Cuisine',
                'en' => 'Kitchen',
                'zh' => '厨房',
            ],
            'sensors' => [
                [
                    'type' => 'temperature',
                    'entity_id' => '$cuisineTemp',
                    'icon' => '🌡️',
                    'name' => [
                        'fr' => 'Température',
                        'en' => 'Temperature',
                        'zh' => '温度',
                    ],
                ],
                [
                    'type' => 'humidity',
                    'entity_id' => '$cuisineHum',
                    'icon' => '💧',
                    'name' => [
                        'fr' => 'Humidité',
                        'en' => 'Humidity',
                        'zh' => '湿度',
                    ],
                ],
            ],
        ],

PHP;
    }

    $config .= <<<PHP
    ],

    'default_sensor_group' => 'yy_room',
];

PHP;

    if (file_put_contents($configFile, $config)) {
        echo "\n✅ config.php 创建成功!\n";
        echo "\n📋 配置内容:\n";
        echo str_repeat("-", 60) . "\n";
        echo $config;
        echo str_repeat("-", 60) . "\n";
        echo "\n🎯 现在可以访问 sensors.php 测试了!\n\n";
    } else {
        die("❌ 无法写入 config.php\n");
    }

} else {
    // 添加 Cuisine 到现有配置
    $config = require $configFile;

    echo "\n输入 Cuisine 传感器信息:\n";
    echo "Cuisine 温度 entity_id: ";
    $cuisineTemp = trim(fgets(STDIN));

    echo "Cuisine 湿度 entity_id: ";
    $cuisineHum = trim(fgets(STDIN));

    if ($cuisineTemp && $cuisineHum) {
        // 检查是否已有 Cuisine
        $hasCuisine = false;
        foreach ($config['sensor_groups'] as $group) {
            if ($group['id'] === 'cuisine') {
                $hasCuisine = true;
                break;
            }
        }

        if (!$hasCuisine) {
            $config['sensor_groups'][] = [
                'id' => 'cuisine',
                'name' => [
                    'fr' => 'Cuisine',
                    'en' => 'Kitchen',
                    'zh' => '厨房',
                ],
                'sensors' => [
                    [
                        'type' => 'temperature',
                        'entity_id' => $cuisineTemp,
                        'icon' => '🌡️',
                        'name' => [
                            'fr' => 'Température',
                            'en' => 'Temperature',
                            'zh' => '温度',
                        ],
                    ],
                    [
                        'type' => 'humidity',
                        'entity_id' => $cuisineHum,
                        'icon' => '💧',
                        'name' => [
                            'fr' => 'Humidité',
                            'en' => 'Humidity',
                            'zh' => '湿度',
                        ],
                    ],
                ],
            ];

            // 写回文件
            $configCode = "<?php\nreturn " . var_export($config, true) . ";\n";
            if (file_put_contents($configFile, $configCode)) {
                echo "\n✅ Cuisine 配置已添加!\n\n";
            } else {
                die("❌ 无法写入配置文件\n");
            }
        } else {
            echo "\n⚠️  Cuisine 配置已存在\n";
        }
    }
}

echo "✨ 完成!\n\n";
